// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package weather

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (SourceConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"appid": {
			Default:     "",
			Description: "your unique API key (you can always find it on your account page under https://home.openweathermap.org/api_keys)",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"city": {
			Default:     "new york",
			Description: "city name to get the current weather for, ex: California, San Francisco, london. you can find the cities list {city.list.json.gz} on http://bulk.openweathermap.org/sample/",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"pollingPeriod": {
			Default:     "5m",
			Description: "how often the connector will get data from the url",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"units": {
			Default:     "imperial",
			Description: "units of measurement, for Fahrenheit use imperial, for Celsius use metric, for Kelvin use standard.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"imperial", "standard", "metric"}},
			},
		},
		"url": {
			Default:     "https://api.openweathermap.org/data/2.5/weather",
			Description: "url that contains the weather data",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
	}
}
